ollama:
  enabled: false

ollamaUrls:
  - http://host.rancher-desktop.internal:11434

ingress:
  enabled: true
  class: traefik
  host: "hermitbook.local"
  hosts:
    - host: "hermitbook.local"
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  storageClass: local-path
  size: 2Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
