ollama:
  enabled: false

ollamaUrls:
  - http://host.rancher-desktop.internal:11434

ingress:
  enabled: true
  class: traefik
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-webui-tls

persistence:
  enabled: true
  storageClass: local-path
  size: 2Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
