tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'awscli'
brew 'docker-credential-helper'
brew 'fd'
brew 'go'
brew 'helm'
brew 'jq'
brew 'kubectl'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'pre-commit'
brew 'pure'
brew 'python'
brew 'ripgrep'
brew 'terraform-docs'
brew 'terraform-ls'
brew 'terragrunt'
brew 'tfk8s'
brew 'tfsec'
brew 'tmux'
brew 'tmux-mem-cpu-load'
brew 'tree'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'alacritty'
cask 'docker'
cask 'font-hack-nerd-font'
cask 'rectangle'
cask 'slack'

mas 'AdGuard for Safari', id: 1440147259

