tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'awscli'
brew 'bash-language-server'
brew 'diff-so-fancy'
brew 'docker-credential-helper'
brew 'exa'
brew 'go'
brew 'gopls'
brew 'gotop'
brew 'helm'
brew 'jq'
brew 'kubectl'
brew 'lua-language-server'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'pre-commit'
brew 'pyright'
brew 'python'
brew 'ripgrep'
brew 'starship'
brew 'terraform-docs'
brew 'terraform-ls'
brew 'terragrunt'
brew 'tfk8s'
brew 'tfsec'
brew 'trash'
brew 'yaml-language-server'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'docker'
cask 'font-hack-nerd-font'
cask 'kitty'
cask 'rectangle'
cask 'slack'

mas 'AdGuard for Safari', id: 1440147259

