tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'romkatv/powerlevel10k'

brew 'awscli'
brew 'bat'
brew 'bottom'
brew 'coreutils'
brew 'delve'
brew 'direnv'
brew 'dive'
brew 'exa'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'gnu-sed'
brew 'go'
brew 'gomodifytags'
brew 'gopls'
brew 'gotests'
brew 'grex'
brew 'jq'
brew 'k9s'
brew 'kubectx', args: ['ignore-dependencies']
brew 'mas'
brew 'neovim'
brew 'node'
brew 'powerlevel10k'
brew 'prettier'
brew 'pre-commit'
brew 'python'
brew 'ripgrep'
brew 'shellcheck'
brew 'shfmt'
brew 'staticcheck'
brew 'terraform'
brew 'terraform-docs'
brew 'terraformer'
brew 'terragrunt'
brew 'tfk8s'
brew 'tflint'
brew 'tfsec'
brew 'tmux'
brew 'tmux-mem-cpu-load'
brew 'trash'
brew 'virtualenv'
brew 'yq'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'alacritty', args: { 'no-quarantine': true }
cask 'font-hack-nerd-font'
cask 'microsoft-teams'
cask 'mouse-fix', args: { 'no-quarantine': true }
cask 'openemu', args: { 'no-quarantine': true } if ENV['USER'] == 'hermitmaster'
cask 'rancher'
cask 'rectangle'
cask 'slack'
cask 'zoom'

mas 'AdGuard for Safari', id: 1440147259
mas 'Vimari', id: 1480933944

