# frozen_string_literal: true

brew 'aws-sso-cli'
brew 'awscli'
brew 'bat'
brew 'bottom'
brew 'cobra-cli'
brew 'coreutils'
brew 'csvkit'
brew 'd2'
brew 'dasel'
brew 'direnv'
brew 'docker'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'go'
brew 'grex'
brew 'grpcurl'
brew 'helm'
brew 'jq'
brew 'k9s'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'lazydocker'
brew 'lazygit'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'ollama'
brew 'podman'
brew 'podman-compose'
brew 'powerlevel10k'
brew 'python'
brew 'ripgrep'
brew 'ruby'
brew 'stern'
brew 'terraform'
brew 'terraform-docs'
brew 'terraformer'
brew 'typescript'
brew 'wget'
brew 'yarn'
brew 'yq'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'font-hack-nerd-font'
cask 'keymapp'
cask 'podman-desktop'
cask 'rectangle'
cask 'wezterm'

mas 'AdGuard for Safari', id: 1_440_147_259
mas 'Vimari', id: 1_480_933_944

if ENV['USER'] == 'hermitmaster'
  cask 'openemu', args: { 'no-quarantine': true }
  cask 'steam'
else
  tap 'fluxcd/tap'
  tap 'del/cloud15', 'ssh://git@hq-stash.corp.proofpoint.com:7999/del/homebrew-cloud15.git'
  tap 'del/cloud15-internal', 'ssh://git@hq-stash.corp.proofpoint.com:7999/del/homebrew-cloud15-internal.git'

  brew 'aws-iam-authenticator'
  brew 'azure-cli'
  brew 'cdk8s'
  brew 'cdktf'
  brew 'cmctl'
  brew 'crane'
  brew 'del/cloud15-internal/namespace-creator'
  brew 'del/cloud15/c15-onelogin-client'
  brew 'fluxcd/tap/flux'
  brew 'gh'
  brew 'git-remote-codecommit'
  brew 'gradle'
  brew 'groovy'
  brew 'kubeconform'
  brew 'kubent'
  brew 'kustomize'
  brew 'maven'
  brew 'opa'
  brew 'openjdk'

  cask 'goland'
  cask 'visual-studio-code'
  cask 'yubico-authenticator'
  cask 'yubico-yubikey-manager'
end
