add_newline = false

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$nodejs\
$python\
$rust\
$terraform\
$cmd_duration\
$jobs\
$status\
$character"""

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
format = "[$branch]($style) "

[hostname]
format =  "[$hostname]($style) "

[terraform]
format = "[$symbol $workspace]($style) "
