format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$golang\
$helm\
$python\
$terraform\
$aws\
$sudo\
$cmd_duration\
$jobs\
$status\
$character"""


[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
symbol = ' '

[cmd_duration]
format = '[$duration ]($style)'
style = '8'

[directory]
style = 'blue bold'
read_only = ' '

[docker_context]
symbol = ' '

[git_branch]
format = '[$symbol$branch ]($style)'
symbol = ' '

[golang]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[python]
symbol = ' '

[terraform]
symbol = ' '

