format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$character"""

right_format = """$all"""

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
symbol = ' '

[cmd_duration]
format = '[$duration ]($style)'
style = '8'

[conda]
format = '[$symbol$environment ]($style)'
symbol = ' '

[dart]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[deno]
format = '[${symbol}(${version} )]($style)'

[directory]
style = 'blue bold'
read_only = ' '

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[git_branch]
format = '[$symbol$branch ]($style)'
symbol = ' '

[golang]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[hg_branch]
format = '[$symbol$branch ]($style)'
symbol = ' '

[java]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[julia]
symbol = ' '

[line_break]
disabled = true

[memory_usage]
symbol = ' '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[package]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[perl]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[php]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[python]
symbol = ' '

[ruby]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[rust]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[scala]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[shlvl]
symbol = ' '

[swift]
symbol = 'ﯣ '

[terraform]
symbol = ' '

