if (($+commands[git])); then
  autoload -Uz compdef
  # Aliases
  alias g='git'
  alias ga='git add'
  alias gaa='git add --all'
  alias gapa='git add --patch'
  alias gau='git add --update'
  alias gav='git add --verbose'
  alias gb='git branch'
  alias gba='git branch -a'
  alias gbd='git branch -d'
  alias gbda='git branch --no-color --merged | command grep -vE "(^\*|master|main|dev|devel|development|staging|release)" | command xargs -n 1 git branch -d'
  alias gbl='git blame -b -w'
  alias gbnm='git branch --no-merged'
  alias gbr='git branch --remote'
  alias gbs='git bisect'
  alias gbsb='git bisect bad'
  alias gbsg='git bisect good'
  alias gbsr='git bisect reset'
  alias gbss='git bisect start'
  alias gc='git commit -v'
  alias 'gc!'='git commit -v --amend'
  alias gca='git commit -v -a'
  alias 'gca!'='git commit -v -a --amend'
  alias gcam='git commit -a -m'
  alias gcans='git commit -a -s --no-edit'
  alias gcb='git checkout -b'
  alias gcd='git checkout develop'
  alias gcf='git config --list'
  alias gcl='git clone --recurse-submodules'
  alias gclean='git clean -fd'
  alias gpristine='git reset --hard && git clean -dfx'
  alias gcm='git checkout main'
  alias gcmsg='git commit -m'
  alias gco='git checkout'
  alias gcount='git shortlog -sn'
  alias gcp='git cherry-pick'
  alias gcs='git commit -S'
  alias gd='git diff'
  alias gdca='git diff --cached'
  alias gdt='git diff-tree --no-commit-id --name-only -r'
  alias gf='git fetch'
  alias gfa='git fetch --all --prune'
  alias gfo='git fetch origin'
  alias gg='git gui citool'
  alias gga='git gui citool --amend'
  alias ggpull='git pull origin $(git_current_branch)'
  alias ggpush='git push origin $(git_current_branch)'
  alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
  alias ghh='git help'
  alias gignore='git update-index --assume-unchanged'
  alias gignored='git ls-files -v | grep ^[[:lower:]]'
  alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
  alias gk='gitk --all --branches &!'
  alias gke='gitk --all $(git log -g --pretty=%h) &!'
  alias gl='git pull'
  alias glg='git log --stat'
  alias glgg='git log --graph'
  alias glgga='git log --graph --decorate --all'
  alias glgm='git log --graph --max-count=10'
  alias glo='git log --oneline --decorate'
  alias glog='git log --oneline --decorate --graph'
  alias gloga='git log --oneline --decorate --graph --all'
  alias glp='git log --pretty=format:"%C(yellow)%h%C(reset) %ad | %s%d [%an]" --graph --date=short'
  alias gm='git merge'
  alias gma='git merge --abort'
  alias gmt='git mergetool --no-prompt'
  alias gmtvim='git mergetool --no-prompt --tool=vimdiff'
  alias gp='git push'
  alias gpd='git push --dry-run'
  alias gpf='git push --force-with-lease'
  alias gpoat='git push origin --all && git push origin --tags'
  alias gpr='git pull --rebase'
  alias gpt='git push --tags'
  alias gr='git remote'
  alias gra='git remote add'
  alias grb='git rebase'
  alias grba='git rebase --abort'
  alias grbc='git rebase --continue'
  alias grbi='git rebase -i'
  alias grbm='git rebase main'
  alias grbs='git rebase --skip'
  alias grep='git grep'
  alias grh='git reset'
  alias grhh='git reset --hard'
  alias grm='git rm'
  alias grmc='git rm --cached'
  alias grmv='git remote rename'
  alias grrm='git remote remove'
  alias grs='git restore'
  alias grset='git remote set-url'
  alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
  alias gru='git reset --'
  alias grup='git remote update'
  alias grv='git remote -v'
  alias gsb='git status -sb'
  alias gsd='git svn dcommit'
  alias gsh='git show'
  alias gsi='git submodule init'
  alias gsps='git show --pretty=short --show-signature'
  alias gsr='git svn rebase'
  alias gss='git status -s'
  alias gst='git status'
  alias gsta='git stash push'
  alias gstaa='git stash apply'
  alias gstall='git stash --all'
  alias gstc='git stash clear'
  alias gstd='git stash drop'
  alias gstl='git stash list'
  alias gstp='git stash pop'
  alias gsts='git stash show --text'
  alias gsu='git submodule update'
  alias gsw='git switch'
  alias gswc='git switch -c'
  alias gts='git tag -s'
  alias gtv='git tag | sort -V'
  alias gunignore='git update-index --no-assume-unchanged'
  alias gunwip='git log -n 1 | grep -q -c "--wip--" && git reset HEAD~1'
  alias gup='git pull --rebase'
  alias gvt='git verify-tag'
  alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
  alias gwt='git worktree'

  # Functions
  git_current_branch() {
    git rev-parse --abbrev-ref HEAD 2>/dev/null
  }

  git_current_commit() {
    git rev-parse HEAD 2>/dev/null
  }

  git_root() {
    git rev-parse --show-toplevel 2>/dev/null
  }

  # Completion for aliases
  compdef _git g ga gaa gapa gau gav gb gba gbd gbda gbl gbnm gbr gbs gbsb gbsg gbsr gbss gc 'gc!' gca 'gca!' gcam gcans gcb gcd gcf gcl gclean gpristine gcm gcmsg gco gcount gcp gcs gd gdca gdt gf gfa gfo gg gga ggpull ggpush ggsup ghh gignore gignored git-svn-dcommit-push gk gke gl glg glgg glgga glgm glo glog gloga glp gm gma gmt gmtvim gp gpd gpf gpoat gpr gpt gr gra grb grba grbc grbi grbm grbs grep grh grhh grm grmc grmv grrm grs grset grt gru grup grv gsb gsd gsh gsi gsps gsr gss gst gsta gstaa gstall gstc gstd gstl gstp gsts gsu gsw gswc gts gtv gunignore gunwip gup gvt gwch gwt
fi
