# frozen_string_literal: true

tap 'homebrew/services'

brew 'bat'
brew 'bottom'
brew 'cobra-cli'
brew 'coreutils'
brew 'd2'
brew 'delta'
brew 'direnv'
brew 'doggo'
brew 'dyff'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gci'
brew 'gh'
brew 'git'
brew 'go'
brew 'golangci-lint'
brew 'gomodifytags'
brew 'gotests'
brew 'hashicorp/tap/terraform'
brew 'jq'
brew 'k9s'
brew 'lazygit'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'ollama'
brew 'powerlevel10k'
brew 'pre-commit'
brew 'python'
brew 'ripgrep'
brew 'terraform-docs'
brew 'typescript'
brew 'wget'
brew 'yq'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'chatgpt'
cask 'keymapp'
cask 'rancher'
cask 'rectangle'
cask 'visual-studio-code'
cask 'wezterm'

mas 'AdGuard for Safari', id: 1_440_147_259
mas 'Vimari', id: 1_480_933_944

if ENV['USER'] == 'hermitmaster'
  cask 'openemu', args: { 'no-quarantine': true }
  cask 'steam'
else
  tap 'hashicorp/tap'
  tap 'fluxcd/tap'

  brew 'awscli'
  brew 'aws-iam-authenticator'
  brew 'aws-sso-cli'
  brew 'azure-cli'
  brew 'cdk8s'
  brew 'cmctl'
  brew 'csvkit'
  brew 'dasel'
  brew 'flux'
  brew 'git-remote-codecommit'
  brew 'kubeconform'
  brew 'kubectx'
  brew 'kubent'
  brew 'opa'
  brew 'ruby'
  brew 'yarn'

  cask 'yubico-authenticator'
  cask 'yubico-yubikey-manager'

  if ENV['CLOUD15_INTERNAL_HOMEBREW_TAP_URL']
    tap 'del/cloud15-internal', ENV['CLOUD15_INTERNAL_HOMEBREW_TAP_URL']
    brew 'del/cloud15-internal/namespace-creator'    # Internal namespace management
  end
  if ENV['CLOUD15_HOMEBREW_TAP_URL']
    tap 'del/cloud15', ENV['CLOUD15_HOMEBREW_TAP_URL']
    brew 'del/cloud15/c15-onelogin-client'          # OneLogin SSO client
    brew 'del/cloud15/quartermaster@2'              # Internal deployment tool
  end
end
