tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'antigen'
brew 'awscli'
brew 'bash-language-server'
brew 'bat'
brew 'delve'
brew 'diff-so-fancy'
brew 'docker-credential-helper'
brew 'exa'
brew 'fd'
brew 'git-delta'
brew 'go'
brew 'gomodifytags'
brew 'gopls'
brew 'gotests'
brew 'gotop'
brew 'helm'
brew 'jq'
brew 'kubectl'
brew 'lazygit'
brew 'lua-language-server'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'pre-commit'
brew 'pure'
brew 'pyright'
brew 'python'
brew 'ripgrep'
brew 'starship'
brew 'staticcheck'
brew 'terraform-docs'
brew 'terraform-ls'
brew 'terragrunt'
brew 'tfk8s'
brew 'tfsec'
brew 'trash'
brew 'yaml-language-server'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'docker'
cask 'font-hack-nerd-font'
cask 'kitty'
cask 'rectangle'
cask 'retroarch-metal' if ENV['USER'] == 'hermitmaster'
cask 'slack' unless ENV['USER'] == 'hermitmaster'

mas 'AdGuard for Safari', id: 1440147259

