# frozen_string_literal: true

tap 'anomalyco/tap', trusted: true
tap 'hashicorp/tap', trusted: true
tap 'homebrew/services'

brew 'anomalyco/tap/opencode'
brew 'argocd'
brew 'awscli'
brew 'aws-sso-cli'
brew 'bat'
brew 'bottom'
brew 'cmctl'
brew 'conftest'
brew 'direnv'
brew 'eza'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-filter-repo'
brew 'gitleaks'
brew 'gnu-sed'
brew 'go'
brew 'gomodifytags'
brew 'gotests'
brew 'grpcurl'
brew 'hashicorp/tap/terraform'
brew 'jq'
brew 'k3d'
brew 'k9s'
brew 'kind'
brew 'kubebuilder'
brew 'kubeconform'
brew 'kubectx'
brew 'kubeseal'
brew 'kustomize'
brew 'lazygit'
brew 'luajit'
brew 'mas'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'ollama'
brew 'openjdk@21'
brew 'pre-commit'
brew 'pure'
brew 'python'
brew 'skaffold'
brew 'starship'
brew 'terraform-docs'
brew 'terragrunt'
brew 'tf-summarize'
brew 'tree-sitter-cli'
brew 'typescript'
brew 'uutils-coreutils'
brew 'uutils-findutils'
brew 'uv'
brew 'watch'
brew 'wget'
brew 'yaml-language-server'
brew 'yamllint'
brew 'yarn'
brew 'yq'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'claude-code@latest'
cask 'keymapp'
cask 'obsidian'
cask 'rancher'
cask 'rectangle'
cask 'wezterm'

mas 'AdGuard for Safari', id: 1_440_147_259
mas 'Keynote',             id: 409_183_694
mas 'Numbers',             id: 409_203_825
mas 'OneLogin for Safari', id: 1_475_824_389
mas 'Pages',               id: 409_201_541
mas 'Xcode',               id: 497_799_835

if ENV['USER'] == 'hermitmaster'
  cask 'openemu', args: { 'no-quarantine': true }
else
  tap 'Azure/kubelogin', trusted: true

  brew 'azure-cli'
  brew 'Azure/kubelogin/kubelogin'
  brew 'snyk-cli'

  cask 'yubico-authenticator'
end
