#!/usr/bin/env zsh

function bootstrap {
  if [[ ! -x "$HOMEBREW_PREFIX/bin/brew" ]]; then
    echo "Homebrew not found. Installing..."
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  auotload -Uz link_configs uatt
  link_configs
  uatt
}
