#!/usr/bin/env zsh

function callenv {
  local image_tag="2.4"
  docker run -it \
    -v "$HOME/work/github/cloud15-infra/namespace.yaml:/namespace.yaml" \
    "repocache.nonprod.ppops.net/dev-docker-local/cloud15callenv:$image_tag"
}
