#!/usr/bin/env zsh

# This script creates symbolic links for configuration files from a specified
# directory to the home directory. This is primarily used for linking
# configuration files for zsh and other tools that expect to find their
# configurations in the home directory.
function link_configs {
  base_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
  dest_dir="${HOME}"
  files=(
    "zsh/.zshenv"
    "zsh/.zshrc"
    ".editorconfig"
    ".prettierrc"
  )

  for file in "${files[@]}"; do
    src_file="${base_dir}/$file"
    dest_file="${dest_dir}/$(basename "$file")"

    if [[ -f "$src_file" ]]; then
      if [[ ! -L "$dest_file" ]]; then
        echo "Linking $src_file to $dest_file"
        ln -fs "$src_file" "$dest_file"
      else
        echo "Skipping $file, already linked"
      fi
    else
      echo "Source file $src_file does not exist, skipping."
    fi
  done
}
