#!/usr/bin/env zsh

function pkopssetup {
  local registry=$PKOPS_ARTIFACTORY
  local tag=$PKOPS_VERSION

  mkdir -p "$HOME/.pkops"
  mkdir -p "$HOME/.aws"
  touch "$HOME/.bash_history"

  docker run -v "$HOME:/home/xbuild $registry/pkops:$tag setup --yes"
}
