map <localleader>a <cmd>Terraform apply<cr>
map <localleader>d <cmd>Terraform destroy<cr>
map <localleader>g <cmd>Terraform get<cr>
map <localleader>i <cmd>Terraform init<cr>
map <localleader>p <cmd>Terraform plan<cr>
map <localleader>r <cmd>Terraform refresh<cr>
map <localleader>t <cmd>Terraform taint<cr>
map <localleader>u <cmd>Terraform untaint<cr>
map <localleader>v <cmd>Terraform validate<cr>
