k9s:
  disablePodCounting: false
  liveViewAutoRefresh: true
  logger:
    buffer: 10000
    showTime: true
    sinceSeconds: -1
    tail: 500
    textWrap: true
  maxConnRetry: 5
  readOnly: false
  screenDumpDir: /Users/drausch/Library/Application Support/k9s/screen-dumps
  skipLatestRevCheck: true
  ui:
    crumbsless: true
    enableMouse: true
    headless: false
    logoless: true
    noIcons: false
    skin: tokyonight_moon
