export XDG_CONFIG_HOME="${HOME}/.config"
export BAT_THEME="Monokai Extended"
export CLICOLOR=1
export EDITOR=nvim
export HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME}/.Brewfile"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export NPM_CONFIG_PREFIX="${HOME}/.local"
export PATH="${HOME}/.local/bin:/opt/homebrew/bin:${PATH}"
export TIME_STYLE="long-iso"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

SHELL_SESSIONS_DISABLE=1

