export XDG_CONFIG_HOME="${HOME}/.config"
export CLICOLOR=1
export EDITOR=nvim
export HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME}/.Brewfile"
export NPM_CONFIG_PREFIX="${HOME}/.local"
export PATH="${HOME}/.local/bin:/opt/homebrew/bin:${PATH}"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

SHELL_SESSIONS_DISABLE=1

test -L "${HOME}/.zshenv" || ln -fs "${HOME}/.config/zsh/zshenv" "${HOME}/.zshenv"
test -f "${HOMEBREW_BUNDLE_FILE}.lock.json" || brew bundle install

